heat_template_version: 2013-05-23

description: >
  Create an isolated network for use with an
  Alces compute environment.

resources:
  cluster_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: cluster_name }

  cluster_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: cluster_network }
      cidr: 10.75.0.0/16
      gateway_ip: 10.75.0.254
      dns_nameservers: [ "8.8.8.8", "8.8.4.4" ]
      allocation_pools:
        - start: 10.75.0.2
          end: 10.75.0.253

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: public

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: cluster_subnet }

  cluster_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { get_param: cluster_name }
      description: Enable ping/SSH
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22

outputs:
  network_id:
    description: Cluster network ID
    value: { get_resource: cluster_network }

  subnet_id:
    description: Cluster subnet ID
    value: { get_resource: cluster_subnet }
