heat_template_version: 2013-05-23

description: >
  Add an Alces Storage Manager appliance to your existing environment

parameters:
  cluster_name:
    type: string
    label: Cluster name
    description: Enter the cluster name

  image:
    type: string
    label: Compute image
    description: Select the Alces Compute image to use
    constraints:
    - custom_constraint: glance.image

  cluster_network_id:
    type: string
    label: Cluster network ID
    description: Enter the unique cluster network ID
    constraints:
      - custom_constraint: neutron.network

  cluster_subnet_id:
    type: string
    label: Cluster subnet ID
    description: Enter the unique cluster subnet ID
    constraints:
      - custom_constraint: neutron.subnet

  admin_key:
    type: string
    label: Admin keypair
    description: Select your keypair to use
    constraints:
      - custom_constraint: nova.keypair

  cluster_uuid:
    type: string
    label: Cluster unique ID
    description: Enter the cluster unique ID

  cluster_token:
    type: string
    label: Cluster unique token
    description: Enter the cluster unique token

resources:
  master_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
            write_files:
            - path: /opt/clusterware/etc/config.yml
              permissions: '0640'
              owner: root:root
              content:
                str_replace:
                  template: |
                    cluster:
                      uuid: '%UUID%'
                      token: '%TOKEN%'
                      name: '%CLUSTER_NAME%'
                      role: 'appliance'
                      tags:
                        appliance_roles: ':storage:'
                  params:
                    "%CLUSTER_NAME%": { get_param: cluster_name }
                    "%UUID%": { get_param: cluster_uuid }
                    "%TOKEN%": { get_param: cluster_token }

  storage_manager:
    type: OS::Nova::Server
    properties:
      name: storage_manager
      image: { get_param: image }
      flavor: m1.medium 
      key_name: { get_param: admin_key }
      networks:
        - port: { get_resource: storage_manager_port }
      user_data_format: RAW
      user_data: { get_resource: master_config }

  storage_manager_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: cluster_network_id }
      fixed_ips:
        - subnet_id: { get_param: cluster_subnet_id }

  storage_manager_access:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public
      port_id: { get_resource: storage_manager_port }

outputs:
  storage_manager_public_ip:
    description: Access IP of Alces Storage Manager
    value: { get_attr: [ storage_manager_access, floating_ip_address ] }
